### PR TITLE
Add navie and remove explore appmaps and runtime analysis

### PR DESCRIPTION
**Pull request by ahtrotta**
Removes `Explore AppMaps` and `Runtime Analysis` from the instructions tree and adds `Ask AppMap Navie AI`:

image

Clicking on `Ask AppMap Navie AI` will open the Navie chat interface. 

When a user creates their first AppMap, they will see this message:

image

If they click `Try Navie` then the Navie chat interface will open.

### CODE REVIEW

**Comment by kgilpin** [comment]
Just as a reminder, keep this in Draft for now.

**Comment by ahtrotta** [comment]
> Just as a reminder, keep this in Draft for now.

Yup, I just wanted to push this to GH just so that there's a copy outside of my laptop.

**Comment by kgilpin** [comment]
I will try this out, can you post a vsix?

**Review by kgilpin — APPROVED** [review]
Worked as designed for me 👍

**Pull request merged**
