### PR TITLE
Runtime Analysis is determined complete on multiple checks.

### PR DESCRIPTION
**Pull request by moxw**
Fixes: [#1403](https://github.com/getappmap/appmap-js/issues/1403)

feat(projectStateService.ts): enhance hasInvestigatedFindings check
test(instructions.test.ts): add test for runtime analysis status transitions

### CODE REVIEW

**Review by ahtrotta — CHANGES_REQUESTED** [review]
Apologies for not letting you know earlier, but we don't want to add system tests because they seem to be inherently flaky and fail intermittently. Can you make the system tests into integration tests or unit tests? Thanks!

**Comment by moxw** [comment]
> Apologies for not letting you know earlier, but we don't want to add system tests because they seem to be inherently flaky and fail intermittently. Can you make the system tests into integration tests or unit tests? Thanks!

Added integration tests, have used `repeatUntil` otherwise it used to fail. Let me know if that's alright.

**Comment by ahtrotta** [comment]
Thanks for converting the system test into an integration test. Using `repeatUntil` is fine.

I just tested this out, and if I generate maps, but don't complete the `Explore AppMaps` step, then I click on the `Runtime Analysis` step it shows a confusing message that setup is complete for the project:

image

Can you make it so that the `Runtime analysis` step is only marked as completed if all of the other instruction steps are completed? Thanks!

**Review by ahtrotta — DISMISSED** [review]
Excellent, thanks @moxw! The code looks good and I tested this change and it works well.

**Review by ahtrotta — CHANGES_REQUESTED** [review]
It looks like your changes caused one of the system tests to fail. Can you fix that? Thanks!

**Comment by moxw** [comment]
> It looks like your changes caused one of the system tests to fail. Can you fix that? Thanks!

Fixed.

**Pull request merged**
