### PR TITLE
feat: Add walkthrough

### LINKED ISSUE #1000: Walkthrough

### PR DESCRIPTION
**Pull request by dividedmind**
image
image
image
image
image

Fixes #1000

### CODE REVIEW

**Comment by kgilpin** [comment]
Thanks Rafal. Some feedback from Elizabeth 

Primary guideline is to make the steps value based.

For example, the value of configuring the model is to use your own key or other secure LLM. 

The value of making runtime data is to improve the performance and accuracy of responses. 

So the user should understand what is to be gained from each step.

**Comment by kgilpin** [comment]
Works with your preferred LLM model backends

Understand your application using chat and get diagrams. 

Solve issues end to end including planning, tests, troubleshooting, code generation, and review

Enhance your AIs knowledge base with runtime data using AppMap language libraries

**Comment by kgilpin** [comment]
## Model configuration

`Your data - your choice of model` Works with popular model backends - must callout Copilot because people don't know that Copilot can be a model backend.

AppMap uses GPT-4o by default, however you can configure it to use the model of your choice, OR you can use GitHub Copilot as a backend.

**Comment by kgilpin** [comment]
## Ask Navie

Missing word "a" - ask about "a" code selection or "your" code selection.

Should describe the functionality with or without a code selection.

## Actions

Button should open Navie Chat

**Comment by kgilpin** [comment]
## Solve issues with Navie

Solve issues end to end including planning, tests, troubleshooting, code generation, and review



## Action

**Comment by kgilpin** [comment]
## Enhance your AIs knowledge base 

Use AppMap libraries to improve the performance and accuracy of Navie's answers with runtime data

## Actions

**Comment by dividedmind** [comment]
> ## Use your preferred AI model
> 
> `Your data - your choice of model` Works with popular model backends - must callout Copilot because people don't know that Copilot can be a model backend.
> 
> "Works with your preferred chat-enabled AI model."
> 
> AppMap uses GPT-4o by default, however you can configure it to use the model of your choice, OR you can use GitHub Copilot as a backend.

image

> ## Actions
> 
> If there is a button here, it could / should open the configurator.

We don't have the configurator yet.

> ## Questions
> 
>     * What is the use default button and what does it do?

Nothing really, just causes the step to be marked as done.

**Comment by dividedmind** [comment]
> ## Ask Navie AI
> 
> "Understand your application using chat, and get diagrams."
> 
> Should describe the functionality with or without a code selection.
> 
> Missing word "a" - ask about "a" code selection or "your" code selection.
> ## Actions
> 
> Button should open Navie Chat

image

**Comment by dividedmind** [comment]
> ## Solve issues with Navie
> 
> Solve issues end to end including planning, tests, troubleshooting, code generation, and review
> 
>     * Paste your issue
> 
>     * Define your plan
> 
>     * Implement the plan with code changes
> 
>     * Troubleshooting and review
> 
> 
> ## Action

image

**Comment by dividedmind** [comment]
> ## Enhance your AIs knowledge base
> 
> Use AppMap libraries to improve the performance and accuracy of your coding and troubleshooting with Navie.
> ## Actions

image

**Comment by dividedmind** [comment]
@kgilpin I've attached the screenshots with your suggestions, but I don't think they work very well.

**Review by kgilpin — APPROVED** [review]

**Pull request merged**
