### PR TITLE
feat: add flame graph setting

### PR DESCRIPTION
**Pull request by lachrist**
This flag is consumed by the peer PR: https://github.com/getappmap/appmap-js/pull/1192

### CODE REVIEW

**Comment by lachrist** [comment]
After installing the vsix, the `flamegraphEnabled` setting showed up but not the flame graph tab was missing.

Screenshot 2023-05-22 at 22 17 20

Screenshot 2023-05-22 at 22 18 44

**Comment by kgilpin** [comment]
If you run the extension in the debugger you can set a breakpoint in the
extension, build the extension and then run with F5

**Comment by lachrist** [comment]
@kgilpin thanks for the tip. I can add breakpoint to `.ts` files but not `.js` files.

And as far as I can tell the main component is loaded inside `web/src/appmapView.js`. https://github.com/getappmap/vscode-appland/blob/0a9b11da2dbf6d837d8dab480fcd6480f8a699ad/web/src/appmapView.js#L23

But vscode is saying that this file is not actually loaded

Screenshot 2023-05-23 at 18 16 52

Screenshot 2023-05-23 at 18 16 36

**Comment by lachrist** [comment]
All seems to work fine. The last thing to do is to update the dependency version of `@appland/components`.
Screenshot 2023-05-23 at 20 45 40

**Comment by kgilpin** [comment]
@lachrist if you want to debug the web view, then in VSCode activate the developer tools - this will give you the standard Chrome debugging tools on the webview. 

Screen Shot 2023-05-24 at 11 17 22 AM

**Comment by kgilpin** [comment]
> @kgilpin thanks again. It came handy to find the real issue: a missing link between the extension and my local version of components.

It's black magic but it's not bad once it's all working.

**Comment by lachrist** [comment]
I don't understand this failure  :(

https://github.com/getappmap/vscode-appland/actions/runs/5145076357/jobs/9262204883?pr=694

It works on my setup with a clean install...

```
lachrist@Laurents-MacBook-Air vscode-appland % yarn test:system


Found existing install in /Users/lachrist/Desktop/workspace/vscode-appland/.vscode-test/vscode-darwin-arm64-1.78.2. Skipping download
  Code object tree
Waiting because: waiting for second iframe
Waiting 200ms because: waiting for second iframe
Waiting 400ms because: waiting for second iframe
    ✓ opening a query code object opens an AppMap (2635ms)

  Findings and scanning
    ✓ automatically identifies findings as AppMaps are created (1115ms)
Waiting because: waiting for second iframe
Waiting 200ms because: waiting for second iframe
    ✓ shows the findings overview page (1392ms)
Waiting because: waiting for second iframe
Waiting 200ms because: waiting for second iframe
Waiting because: waiting for second iframe
Waiting 200ms because: waiting for second iframe
    ✓ opens the findings details page from the findings overview page (1662ms)
Waiting because: waiting for second iframe
Waiting 200ms because: waiting for second iframe
    ✓ opens the findings details page from the runtime analysis tree view (1443ms)
    - reuses the finding details webview

  Instructions tree view
    ✓ displays a badge when AppMap installation is pending for an installable project
    ✓ accurately depicts the installation state (12621ms)
Waiting because: Expected page 'Add AppMap to your project' to be visible
Waiting because: Expected page 'Record AppMaps' to be visible
Waiting because: Expected page 'Explore AppMaps' to be visible
Waiting because: Expected page 'Generate OpenAPI' to be visible
Waiting because: Expected page 'AppMap Runtime Analysis' to be visible
    ✓ opens up the expected web views (551ms)
    ✓ re-uses web views (195ms)
    ✓ hides the pending badge upon completing the installation steps (9404ms)
    ✓ can be stepped through as expected (4704ms)

  Findings and scanning
Waiting because: waiting for second iframe
Waiting 200ms because: waiting for second iframe
Waiting because: waiting for second iframe
Waiting 200ms because: waiting for second iframe
Waiting 400ms because: waiting for second iframe
    ✓ opens a map from a findings webview (4306ms)


  12 passing (2m)
  1 pending

```

**Pull request merged**
